# Generated by Django 5.1.4 on 2024-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_object_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='size',
            field=models.PositiveIntegerField(blank=True, max_length=150, null=True, verbose_name='Size'),
        ),
    ]
