# Generated by Django 5.1.4 on 2024-12-12 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_object_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='shared_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared', to=settings.AUTH_USER_MODEL, verbose_name='Shared To'),
        ),
        migrations.AlterField(
            model_name='object',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
