# Generated by Django 5.1.4 on 2024-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_object_shared_to_alter_object_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='Path'),
        ),
    ]
