# Generated by Django 5.1.4 on 2024-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_object_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Size'),
        ),
    ]
