# Generated by Django 5.1.4 on 2024-12-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_object_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
